# Generated by Django 5.0.6 on 2025-03-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                ("firstname", models.IntegerField(primary_key=True, serialize=False)),
                ("lastname", models.CharField(max_length=20)),
                ("travelpoints", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
